MODE_SUBSCRIBE = "subscribe"
MODE_SUBSCRIBED = "subscribed"
MODE_UNSUBSCRIBED = "unsubscribed"
MODE_DEFAULT = "default"
MODE_BROADCAST = "broadcast"
MODE_FEEDBACK = "feedback"
MODE_ADD_FILE = "add_file"
MODE_ADD_PHOTO = "add_photo"
MODE_ADD_POSTCARD = "add_postcard"
MODE_ADD_BLESSING = "add_blessing"
MODE_ADD_DOCUMENT = "add_document"
MODE_ADD_VIDEO = "add_video"
MODE_LOAD_SUB = "load_sub"

STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
