version: "3.8"


services:
    mongo:
        container_name: mongodb_${project_name}_${mode}
        image: mongo:7.0.5-rc0-jammy
        restart: always
        expose:
            - "27017"
        volumes:
            - ./mongo/mongod.conf:/etc/mongod.conf
            - ./production/mongo:/data/db
        command: mongod
        env_file: ".env"
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 2048M
                reservations:
                    cpus: "1"
                    memory: 512M
    
    master_bot:
        container_name: master_${project_name}_${mode}
        build: ./master
        restart: always
        command: python3 bot/bot.py
        depends_on:
            - mongo
        volumes:
            - "./production/error:/error:rw"
            - /var/www/${domain}/html/${project_name}:/online:rw
            - "./shared_config:/code/shared_config"
#           - "./master/config:/code/config"  # Define in Dockerfile
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 2048M

    worker_bot:
        container_name: worker_${project_name}_${mode}
        build: ./worker_1
        restart: always
        command: python3 bot/bot.py
        deploy:
             resources:
                 limits:
                     cpus: "2"
                     memory: 4096M
        volumes:
            - "./production/data:/data:rw"
            - "./production/error:/error:rw"
            - /var/www/${domain}/html/${project_name}:/online:rw
            - "./shared_config:/code/shared_config"
#           - "./worker_1/config:/code/config"  # Define in Dockerfile
        depends_on:
            - mongo
            - master_bot
